apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: cpu-scaledobject
  namespace: worldskills
spec:
  scaleTargetRef:
    name: nginx-deploy   # Nome do deployment alvo (valor Helm)
  minReplicaCount: 2
  maxReplicaCount: 5                      # Sempre defina os limites
  triggers:
    - type: cpu
      metadata:
        type: Utilization
        value: "50"                       # Escala se uso da CPU > 50%
