apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: cpu-scaledobject
  namespace: worldskills
spec:
  scaleTargetRef:
    name: nginx-deploy
  minReplicaCount: 2
  maxReplicaCount: 5
  triggers:
    - type: cpu
      metadata:
        value: "50"
